
import { PrismaClient } from "@prisma/client";
import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "node:crypto";

import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

function createSeedAdminClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRoleKey) {
    throw new Error(
      "Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY before running db:seed.",
    );
  }

  return createClient(url, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

const prisma = new PrismaClient();

const STORAGE_DRIVER = process.env.STORAGE_DRIVER ?? "local";
const STORAGE_DIR = path.resolve(process.cwd(), process.env.STORAGE_LOCAL_DIR ?? ".storage");

function buildPdf(title: string, targetBytes: number): Buffer {
  const body = `BT /F1 18 Tf 40 140 Td (${title.replace(/[()\\]/g, "")}) Tj ET
BT /F1 10 Tf 40 110 Td (Sample document generated by the Vault seed script.) Tj ET`;

  const build = (padding: string) => `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 200]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>endobj
4 0 obj<</Length ${body.length}>>stream
${body}
endstream endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
${padding}trailer<</Root 1 0 R/Size 6>>
%%EOF`;

  const base = build("");
  const shortfall = targetBytes - Buffer.byteLength(base, "utf8");
  const padding = shortfall > 2 ? `%${"0".repeat(shortfall - 2)}\n` : "";

  return Buffer.from(build(padding), "utf8");
}

async function writeSeedObject(storageKey: string, contents: Buffer): Promise<void> {
  if (STORAGE_DRIVER !== "local") return;
  const target = path.join(STORAGE_DIR, storageKey);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, contents);
}

const DEMO_PASSWORD = "demo1234";
const OWNER = { email: "demo@vault.app", name: "Dana Owner" };
const INVITEE = { email: "guest@vault.app", name: "Gene Guest" };

interface FolderSpec {
  name: string;
  files?: Array<{ name: string; size: number }>;
  children?: FolderSpec[];
}

const STRUCTURE: FolderSpec[] = [
  {
    name: "01 — Corporate",
    files: [
      { name: "Certificate of incorporation.pdf", size: 184_320 },
      { name: "Cap table.pdf", size: 96_500 },
    ],
    children: [
      {
        name: "Board minutes",
        files: [
          { name: "2024-01 Board minutes.pdf", size: 61_200 },
          { name: "2024-04 Board minutes.pdf", size: 58_900 },
        ],
      },
    ],
  },
  {
    name: "02 — Financials",
    files: [
      { name: "FY2023 audited accounts.pdf", size: 1_248_000 },
      { name: "FY2024 management accounts.pdf", size: 742_100 },
    ],
    children: [
      {
        name: "Tax",
        files: [{ name: "Corporation tax return 2023.pdf", size: 233_400 }],
      },
    ],
  },
  {
    name: "03 — Legal",
    children: [
      {
        name: "NDAs",
        files: [
          { name: "Mutual NDA — Acme.pdf", size: 88_200 },
          { name: "Mutual NDA — Northwind.pdf", size: 91_050 },
        ],
      },
      {
        name: "Customer contracts",
        files: [{ name: "MSA — Globex.pdf", size: 412_000 }],
      },
    ],
  },
  {
    name: "04 — Commercial",
    files: [{ name: "Pipeline overview.pdf", size: 156_700 }],
  },
];

async function ensureAuthUser(email: string, password: string, name: string) {
  const admin = createSeedAdminClient();
  const normalised = email.toLowerCase();

  const { data: listed, error: listError } = await admin.auth.admin.listUsers({ perPage: 1000 });
  if (listError) throw listError;

  const existing = listed.users.find((user) => user.email?.toLowerCase() === normalised);
  if (existing) {
    const { data, error } = await admin.auth.admin.updateUserById(existing.id, {
      password,
      email_confirm: true,
      user_metadata: { name },
    });
    if (error) throw error;
    return data.user;
  }

  const { data, error } = await admin.auth.admin.createUser({
    email: normalised,
    password,
    email_confirm: true,
    user_metadata: { name },
  });
  if (error) throw error;
  if (!data.user) throw new Error(`Could not create Supabase user for ${email}.`);
  return data.user;
}

async function upsertSeedUser(authId: string, email: string, name: string) {
  const existing = await prisma.user.findUnique({ where: { email } });
  if (existing) {
    if (existing.id !== authId) {
      console.warn(
        `Warning: Prisma User ${email} id=${existing.id} differs from Auth id=${authId}. Keeping Prisma id.`,
      );
    }
    return prisma.user.update({
      where: { email },
      data: { name },
    });
  }
  return prisma.user.create({
    data: { id: authId, email, name },
  });
}

async function main() {
  const ownerAuth = await ensureAuthUser(OWNER.email, DEMO_PASSWORD, OWNER.name);
  const inviteeAuth = await ensureAuthUser(INVITEE.email, DEMO_PASSWORD, INVITEE.name);

  // Keep Prisma User.id aligned with Supabase Auth id when possible.
  const owner = await upsertSeedUser(ownerAuth.id, OWNER.email, OWNER.name);
  const invitee = await upsertSeedUser(inviteeAuth.id, INVITEE.email, INVITEE.name);

  await prisma.dataRoom.deleteMany({ where: { ownerId: owner.id } });

  const dataRoomId = randomUUID();
  await prisma.dataRoom.create({
    data: {
      id: dataRoomId,
      name: "Project Atlas — Acquisition",
      description: "Due diligence materials for the Acme Corp. transaction.",
      ownerId: owner.id,
    },
  });

  const rootId = randomUUID();
  await prisma.folder.create({
    data: {
      id: rootId,
      dataRoomId,
      parentId: null,
      name: "All files",
      path: `/${rootId}/`,
      depth: 0,
      createdById: owner.id,
    },
  });

  const created = await createTree(STRUCTURE, {
    dataRoomId,
    parentId: rootId,
    parentPath: `/${rootId}/`,
    depth: 0,
    userId: owner.id,
  });

  const ndaFolder = created.get("NDAs");
  const financials = created.get("02 — Financials");

  if (ndaFolder) {
    await prisma.share.create({
      data: {
        id: randomUUID(),
        dataRoomId,
        subjectType: "FOLDER",
        folderId: ndaFolder,
        mode: "PUBLIC_LINK",
        role: "VIEWER",
        token: randomUUID().replaceAll("-", ""),
        createdById: owner.id,
      },
    });
  }

  if (financials) {
    const share = await prisma.share.create({
      data: {
        id: randomUUID(),
        dataRoomId,
        subjectType: "FOLDER",
        folderId: financials,
        mode: "RESTRICTED",
        role: "VIEWER",
        createdById: owner.id,
      },
    });
    await prisma.shareGrant.create({
      data: {
        id: randomUUID(),
        shareId: share.id,
        email: invitee.email,
        userId: invitee.id,
        role: "VIEWER",
      },
    });
  }

  console.log(`Seeded "Project Atlas — Acquisition".

  Owner:   ${OWNER.email} / ${DEMO_PASSWORD}
  Invitee: ${INVITEE.email} / ${DEMO_PASSWORD}  (sees "02 — Financials" under Shared with me)

  Users are created in Supabase Auth and synced to the Prisma "User" table.
${
  STORAGE_DRIVER === "local"
    ? "\n  Real PDF bytes were written to the local blob store, so previews and downloads work."
    : "\n  STORAGE_DRIVER is not 'local', so no bytes were uploaded; seeded files will preview as missing."
}`);
}

interface TreeContext {
  dataRoomId: string;
  parentId: string;
  parentPath: string;
  depth: number;
  userId: string;
}

async function createTree(
  specs: FolderSpec[],
  context: TreeContext,
  index = new Map<string, string>(),
): Promise<Map<string, string>> {
  for (const spec of specs) {
    const folderId = randomUUID();
    const folderPath = `${context.parentPath}${folderId}/`;

    await prisma.folder.create({
      data: {
        id: folderId,
        dataRoomId: context.dataRoomId,
        parentId: context.parentId,
        name: spec.name,
        path: folderPath,
        depth: context.depth + 1,
        createdById: context.userId,
      },
    });
    index.set(spec.name, folderId);

    for (const file of spec.files ?? []) {
      const fileId = randomUUID();
      const versionId = randomUUID();
      const storageKey = `data-rooms/${context.dataRoomId}/objects/${versionId}.pdf`;

      const contents = buildPdf(file.name.replace(/\.pdf$/i, ""), file.size);
      await writeSeedObject(storageKey, contents);

      await prisma.file.create({
        data: {
          id: fileId,
          dataRoomId: context.dataRoomId,
          folderId,
          name: file.name,
          mimeType: "application/pdf",
          size: contents.byteLength,
          versionCount: 1,
          createdById: context.userId,
        },
      });
      await prisma.fileVersion.create({
        data: {
          id: versionId,
          fileId,
          versionNumber: 1,
          size: contents.byteLength,
          mimeType: "application/pdf",
          storageKey,
          uploadedById: context.userId,
        },
      });
      await prisma.file.update({
        where: { id: fileId },
        data: { currentVersionId: versionId },
      });
    }

    if (spec.children) {
      await createTree(
        spec.children,
        {
          ...context,
          parentId: folderId,
          parentPath: folderPath,
          depth: context.depth + 1,
        },
        index,
      );
    }
  }

  return index;
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
